server:
  port: 7070

management:
  security:
    enabled: false

spring:
  application:
    name: zipkin-server

#eureka:
#  client:
#    service-url:
#      defaultZone : "http://localhost:8080/eureka"